serviceAccountName: demo-app
secretName: demo-app

podAnnotations:
  secret.reloader.stakater.com/reload: demo-app

podMatchLabels:
  app: demo-app

podAllLabels:
  app: demo-app
  azure.workload.identity/use: "true"

service:
  type: ClusterIP
  port: 8080

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 30
  successThreshold: 2
  failureThreshold: 2

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "azure/application-gateway"
    appgw.ingress.kubernetes.io/health-probe-unhealthy-threshold: "2"
    appgw.ingress.kubernetes.io/request-timeout: "30"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"  
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"