replicaCount: 1
serviceAccountName: ""
vaultUrl: ""
minReplicas: 1
maxReplicas: 2

image:
  repository: nginx
  tag: ""

podAnnotations: {}
podMatchLabels: {}
podAllLabels: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  host: ""

resources: {}

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 30
  periodSeconds: 30
  successThreshold: 2
  failureThreshold: 2

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
